// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0hkb3Fq5jnzelK6n7nRQpwrhYD8zXcDo',
    appId: '1:834451867632:web:28ebfb1cbfb61e23a8bf35',
    messagingSenderId: '834451867632',
    projectId: 'flutterfirebase-9a40d',
    authDomain: 'flutterfirebase-9a40d.firebaseapp.com',
    storageBucket: 'flutterfirebase-9a40d.firebasestorage.app',
    measurementId: 'G-M7KNHWD2KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOycCBhr7nFnew8c1eqn9eFHbB2IQ7d_I',
    appId: '1:834451867632:android:0d1f31d099bf06ffa8bf35',
    messagingSenderId: '834451867632',
    projectId: 'flutterfirebase-9a40d',
    storageBucket: 'flutterfirebase-9a40d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5KaHQSGHEtCtifmZHhEMsI0huV_WsQfU',
    appId: '1:834451867632:ios:92b664b2fb38df74a8bf35',
    messagingSenderId: '834451867632',
    projectId: 'flutterfirebase-9a40d',
    storageBucket: 'flutterfirebase-9a40d.firebasestorage.app',
    iosBundleId: 'com.example.cobacoba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5KaHQSGHEtCtifmZHhEMsI0huV_WsQfU',
    appId: '1:834451867632:ios:92b664b2fb38df74a8bf35',
    messagingSenderId: '834451867632',
    projectId: 'flutterfirebase-9a40d',
    storageBucket: 'flutterfirebase-9a40d.firebasestorage.app',
    iosBundleId: 'com.example.cobacoba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0hkb3Fq5jnzelK6n7nRQpwrhYD8zXcDo',
    appId: '1:834451867632:web:e92567b89b4ea85aa8bf35',
    messagingSenderId: '834451867632',
    projectId: 'flutterfirebase-9a40d',
    authDomain: 'flutterfirebase-9a40d.firebaseapp.com',
    storageBucket: 'flutterfirebase-9a40d.firebasestorage.app',
    measurementId: 'G-WE8R6JEBWH',
  );
}
